### PR TITLE
Mapping changes

### PR DESCRIPTION
**Pull request by Mewchild**
Take 3

Fixes: #89, #79, #86
Fixes bugs with General Secretary's office.
Fixes power/atmos/area conflicts in sci and medical.

### CODE REVIEW

**Comment by JakeDaBoss** [comment]
*GASP* IT'S ALIVE. AND IT WORKS!

**Comment by Mewchild** [comment]
Mapmerge. Trying again

**Comment by JakeDaBoss** [comment]
Oh come on. D:

**Comment by Mewchild** [comment]
Shhh I'm fixing it

**Pull request closed without merging**
