### PR TITLE
Sci Checkpoint. Easter Eggs

### PR DESCRIPTION
**Pull request by Mewchild**
Added a security checkpoint to science. Added minor easter eggs.

### CODE REVIEW

**Comment by JakeDaBoss** [comment]
Conflicts. Did you use Map Merger start and finish? :)

**Comment by Mewchild** [comment]
I did. :c

-Jonathon Key

**Comment by JakeDaBoss** [comment]
I'll talk to @Lykayos

**Comment by Mewchild** [comment]
Will redo work. Give me a day.

**Pull request closed without merging**
